#!/usr/bin/env python3
"""Generate the capture-only C++ observation table from Unity fixture v2."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
from pathlib import Path
import sys
from typing import Any


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
VALIDATOR_PATH = REPOSITORY_ROOT / "tools" / "verify-unity-particle-fixture.py"
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "src"
    / "reference"
    / "src"
    / "unity_particle_fixture_v2.generated.inc"
)

SPEC = importlib.util.spec_from_file_location("verify_unity_particle_fixture", VALIDATOR_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError(f"unable to load fixture validator: {VALIDATOR_PATH}")
VERIFY = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(VERIFY)


SYSTEM_CONTRACT = {
    "FX_Touch_ParticleFixture": (0, None),
    "MeshTri": (2, "DissolveRing"),
    "ring": (1, "CenterDisk"),
    "Ring (3)": (4, "Triangle"),
    "Ring (4)": (0, "Triangle"),
}
NATIVE_RENDER_ORDER = {
    "ring": 0,
    "MeshTri": 1,
    "Ring (3)": 2,
    "Ring (4)": 3,
}


def _float_literal(value: Any) -> str:
    number = float(value)
    text = format(number, ".10g")
    if "e" not in text.lower() and "." not in text:
        text += ".0"
    return text + "F"


def _require_fixture_shape(fixture: dict[str, Any]) -> list[dict[str, Any]]:
    systems = fixture["systems"]
    actual_names = [system["name"] for system in systems]
    if actual_names != list(SYSTEM_CONTRACT):
        raise VERIFY.ValidationError(
            "fixture systems must keep the locked root, MeshTri, ring, Ring (3), Ring (4) order"
        )

    for system in systems:
        expected_count, _ = SYSTEM_CONTRACT[system["name"]]
        if system["particleCount"] != expected_count:
            raise VERIFY.ValidationError(
                f"system {system['name']} must contain {expected_count} particles"
            )
        if system["name"] != "FX_Touch_ParticleFixture" and system["simulationSpace"] != "World":
            raise VERIFY.ValidationError(
                f"system {system['name']} must use World simulation space"
            )
    return systems


def _system_scale(system: dict[str, Any]) -> float:
    matrix = system["localToWorldMatrix"]
    scale_x = float(matrix[0])
    scale_y = float(matrix[5])
    if scale_x <= 0.0 or abs(scale_x - scale_y) > 1.0e-6:
        raise VERIFY.ValidationError(
            f"system {system['name']} must have a positive uniform XY scale"
        )
    return scale_x


def _particle_row(system: dict[str, Any], particle: dict[str, Any]) -> list[str]:
    rotation = particle["rotation"]
    if abs(float(rotation["x"])) > 1.0e-6 or abs(float(rotation["y"])) > 1.0e-6:
        raise VERIFY.ValidationError(
            f"system {system['name']} contains a non-planar particle rotation"
        )

    projected = particle["projectedPixel"]
    color = particle["color"]
    custom1 = particle["custom1"]
    _, kind = SYSTEM_CONTRACT[system["name"]]
    return [
        "    UnityParticleObservation{",
        f"        UnityParticleSystemKind::{kind},",
        "        FixturePoint{" + _float_literal(projected["x"]) + ", "
        + _float_literal(projected["y"]) + "},",
        f"        {_float_literal(_system_scale(system))},",
        f"        {_float_literal(particle['size'])},",
        "        FixtureRotation{" + _float_literal(rotation["z"]) + ", "
        + _float_literal(rotation["w"]) + "},",
        "        FixtureColor{"
        + ", ".join(
            _float_literal(color[channel]) for channel in ("r", "g", "b", "a")
        )
        + "},",
        f"        {_float_literal(custom1['x'])},",
        f"        {particle['atlasFrame']}U}},",
    ]


def generate_include(fixture: dict[str, Any], fixture_bytes: bytes) -> bytes:
    systems = _require_fixture_shape(fixture)
    render_systems = sorted(
        (system for system in systems if system["name"] in NATIVE_RENDER_ORDER),
        key=lambda system: NATIVE_RENDER_ORDER[system["name"]],
    )
    rows: list[str] = []
    particle_count = sum(system["particleCount"] for system in render_systems)
    for system in render_systems:
        for particle in system["particles"]:
            rows.extend(_particle_row(system, particle))

    digest = hashlib.sha256(fixture_bytes).hexdigest().upper()
    lines = [
        "// Generated by tools/generate-unity-particle-fixture.py. Do not edit.",
        f'constexpr std::string_view unityParticleFixtureSha256 = "{digest}";',
        f"constexpr std::array<UnityParticleObservation, {particle_count}U>",
        "    unityParticleObservations{{",
        *rows,
        "}};",
        "",
    ]
    return "\n".join(lines).encode("ascii")


def run(fixture_path: Path, output_path: Path, check: bool) -> None:
    fixture, fixture_bytes = VERIFY.load_fixture(fixture_path)
    generated = generate_include(fixture, fixture_bytes)
    if check:
        try:
            current = output_path.read_bytes()
        except OSError as error:
            raise VERIFY.ValidationError(
                f"unable to read generated fixture {output_path}: {error}"
            ) from error
        if current != generated:
            raise VERIFY.ValidationError(
                f"generated fixture is stale: {output_path}"
            )
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(generated)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("fixture", type=Path)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        run(args.fixture, args.output, args.check)
    except (OSError, VERIFY.ValidationError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1
    action = "verified" if args.check else "generated"
    print(f"Unity particle C++ fixture {action}: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
