[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $UnityProjectRoot,

    [string] $OutputPath = (Join-Path $PSScriptRoot '..\src\windows\src\generated_unity_texture_data.inc')
)

$ErrorActionPreference = 'Stop'

$textureDirectory = Join-Path $UnityProjectRoot 'Assets\Imported\FX_Touch\Textures'
$textures = @(
    @{ Name = 'circle01'; File = 'FX_TEX_Circle_01.png' },
    @{ Name = 'gradRing3'; File = 'FX_TEX_Grad_Ring3.png' },
    @{ Name = 'triangle02_1'; File = 'FX_TEX_Triangle_02_1.png' },
    @{ Name = 'trail03'; File = 'FX_TEX_Trail_03.png' }
)

$builder = [System.Text.StringBuilder]::new()
[void] $builder.AppendLine('// Generated by tools/generate-embedded-unity-textures.ps1. Do not edit by hand.')

foreach ($texture in $textures)
{
    $path = Join-Path $textureDirectory $texture.File
    if (-not (Test-Path -LiteralPath $path -PathType Leaf))
    {
        throw "Missing Unity texture: $path"
    }

    [byte[]] $bytes = [System.IO.File]::ReadAllBytes($path)
    $base64 = [Convert]::ToBase64String($bytes)
    [void] $builder.AppendLine("inline constexpr std::string_view $($texture.Name)PngBase64 = R`"bafx(")
    for ($offset = 0; $offset -lt $base64.Length; $offset += 100)
    {
        $length = [Math]::Min(100, $base64.Length - $offset)
        [void] $builder.AppendLine($base64.Substring($offset, $length))
    }
    [void] $builder.AppendLine(')bafx";')
    [void] $builder.AppendLine("inline constexpr std::size_t $($texture.Name)PngByteCount = $($bytes.Length)U;")
}

$resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($resolvedOutput)) | Out-Null
[System.IO.File]::WriteAllText(
    $resolvedOutput,
    $builder.ToString(),
    [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated $resolvedOutput from $($textures.Count) Unity textures."
